# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWin(object):
    def setupUi(self, loginWin):
        loginWin.setObjectName("loginWin")
        loginWin.resize(367, 253)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(loginWin.sizePolicy().hasHeightForWidth())
        loginWin.setSizePolicy(sizePolicy)
        loginWin.setAutoFillBackground(True)
        loginWin.setStyleSheet("")
        loginWin.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(loginWin)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalFrame = QtWidgets.QFrame(loginWin)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_5.setContentsMargins(4, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.from_jid = QtWidgets.QLabel(self.horizontalFrame)
        self.from_jid.setMinimumSize(QtCore.QSize(180, 0))
        self.from_jid.setText("")
        self.from_jid.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.from_jid.setObjectName("from_jid")
        self.horizontalLayout_5.addWidget(self.from_jid)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.top_btn_gb = QtWidgets.QFrame(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_btn_gb.sizePolicy().hasHeightForWidth())
        self.top_btn_gb.setSizePolicy(sizePolicy)
        self.top_btn_gb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.top_btn_gb.setObjectName("top_btn_gb")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.top_btn_gb)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.minimum_btn = QtWidgets.QPushButton(self.top_btn_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimum_btn.sizePolicy().hasHeightForWidth())
        self.minimum_btn.setSizePolicy(sizePolicy)
        self.minimum_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.minimum_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/src/icon/下拉.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimum_btn.setIcon(icon)
        self.minimum_btn.setAutoRepeat(False)
        self.minimum_btn.setFlat(True)
        self.minimum_btn.setObjectName("minimum_btn")
        self.horizontalLayout_6.addWidget(self.minimum_btn)
        self.close_btn = QtWidgets.QPushButton(self.top_btn_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_btn.sizePolicy().hasHeightForWidth())
        self.close_btn.setSizePolicy(sizePolicy)
        self.close_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.close_btn.setStyleSheet("")
        self.close_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/src/icon/关闭.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon1)
        self.close_btn.setDefault(True)
        self.close_btn.setFlat(True)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_6.addWidget(self.close_btn)
        self.horizontalLayout_5.addWidget(self.top_btn_gb)
        self.horizontalLayout_5.setStretch(1, 8)
        self.horizontalLayout_5.setStretch(2, 3)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.line = QtWidgets.QFrame(loginWin)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalWidget_2 = QtWidgets.QWidget(loginWin)
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setVerticalSpacing(9)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.autoLogin = QtWidgets.QCheckBox(self.horizontalWidget_2)
        self.autoLogin.setObjectName("autoLogin")
        self.horizontalLayout_3.addWidget(self.autoLogin)
        self.remeberPwd = QtWidgets.QCheckBox(self.horizontalWidget_2)
        self.remeberPwd.setObjectName("remeberPwd")
        self.horizontalLayout_3.addWidget(self.remeberPwd)
        self.rigister = MyLabel(self.horizontalWidget_2)
        self.rigister.setLineWidth(0)
        self.rigister.setTextFormat(QtCore.Qt.RichText)
        self.rigister.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rigister.setWordWrap(False)
        self.rigister.setIndent(0)
        self.rigister.setOpenExternalLinks(False)
        self.rigister.setObjectName("rigister")
        self.horizontalLayout_3.addWidget(self.rigister)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.login_btn = QtWidgets.QPushButton(self.horizontalWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        self.login_btn.setObjectName("login_btn")
        self.horizontalLayout_4.addWidget(self.login_btn)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.loginPwd = QtWidgets.QLineEdit(self.horizontalWidget_2)
        self.loginPwd.setMinimumSize(QtCore.QSize(0, 30))
        self.loginPwd.setMaxLength(32)
        self.loginPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.loginPwd.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.loginPwd.setObjectName("loginPwd")
        self.horizontalLayout_2.addWidget(self.loginPwd)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginAccount = QtWidgets.QLineEdit(self.horizontalWidget_2)
        self.loginAccount.setMinimumSize(QtCore.QSize(0, 30))
        self.loginAccount.setObjectName("loginAccount")
        self.horizontalLayout.addWidget(self.loginAccount)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.horizontalLayout_7.addLayout(self.formLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.horizontalWidget_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 88)

        self.retranslateUi(loginWin)
        QtCore.QMetaObject.connectSlotsByName(loginWin)

    def retranslateUi(self, loginWin):
        _translate = QtCore.QCoreApplication.translate
        loginWin.setWindowTitle(_translate("loginWin", "登陆"))
        self.autoLogin.setText(_translate("loginWin", "自动登陆"))
        self.remeberPwd.setText(_translate("loginWin", "记住密码"))
        self.rigister.setText(_translate("loginWin", "注册账号"))
        self.login_btn.setText(_translate("loginWin", "登陆"))
from .mylabel import MyLabel
from src import img_rc
