# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(260, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(21)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/src/icon/icon/人群.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow#background-image: url(:/src/images/images/main_bg1.png);")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AnimatedDocks)
        self.win_container = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.win_container.sizePolicy().hasHeightForWidth())
        self.win_container.setSizePolicy(sizePolicy)
        self.win_container.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.win_container.setStyleSheet("")
        self.win_container.setObjectName("win_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.win_container)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.top_btn_gb = QtWidgets.QGroupBox(self.win_container)
        self.top_btn_gb.setObjectName("top_btn_gb")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_btn_gb)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.setting_btn = QtWidgets.QPushButton(self.top_btn_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setting_btn.sizePolicy().hasHeightForWidth())
        self.setting_btn.setSizePolicy(sizePolicy)
        self.setting_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/src/icon/设置_管理.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting_btn.setIcon(icon1)
        self.setting_btn.setAutoRepeat(False)
        self.setting_btn.setFlat(True)
        self.setting_btn.setObjectName("setting_btn")
        self.horizontalLayout.addWidget(self.setting_btn)
        self.minimum_btn = QtWidgets.QPushButton(self.top_btn_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimum_btn.sizePolicy().hasHeightForWidth())
        self.minimum_btn.setSizePolicy(sizePolicy)
        self.minimum_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/src/icon/下拉.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimum_btn.setIcon(icon2)
        self.minimum_btn.setAutoRepeat(False)
        self.minimum_btn.setFlat(True)
        self.minimum_btn.setObjectName("minimum_btn")
        self.horizontalLayout.addWidget(self.minimum_btn)
        self.close_btn = QtWidgets.QPushButton(self.top_btn_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_btn.sizePolicy().hasHeightForWidth())
        self.close_btn.setSizePolicy(sizePolicy)
        self.close_btn.setStyleSheet("")
        self.close_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/src/icon/关闭.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon3)
        self.close_btn.setDefault(True)
        self.close_btn.setFlat(True)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        self.horizontalLayout.setStretch(0, 6)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout_2.addWidget(self.top_btn_gb)
        self.user_info_gb = QtWidgets.QGroupBox(self.win_container)
        self.user_info_gb.setEnabled(True)
        self.user_info_gb.setTitle("")
        self.user_info_gb.setFlat(True)
        self.user_info_gb.setObjectName("user_info_gb")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.user_info_gb)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.avatar = QtWidgets.QToolButton(self.user_info_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.avatar.sizePolicy().hasHeightForWidth())
        self.avatar.setSizePolicy(sizePolicy)
        self.avatar.setMinimumSize(QtCore.QSize(48, 48))
        self.avatar.setStyleSheet("")
        self.avatar.setIconSize(QtCore.QSize(48, 48))
        self.avatar.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.avatar.setAutoRaise(True)
        self.avatar.setArrowType(QtCore.Qt.NoArrow)
        self.avatar.setObjectName("avatar")
        self.horizontalLayout_3.addWidget(self.avatar)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.user_nane = QtWidgets.QLabel(self.user_info_gb)
        self.user_nane.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.user_nane.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.user_nane.setTextFormat(QtCore.Qt.AutoText)
        self.user_nane.setObjectName("user_nane")
        self.verticalLayout_3.addWidget(self.user_nane)
        self.sign = QtWidgets.QLabel(self.user_info_gb)
        self.sign.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sign.setObjectName("sign")
        self.verticalLayout_3.addWidget(self.sign)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.setStretch(2, 2)
        self.verticalLayout_3.setStretch(3, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 12)
        self.verticalLayout_2.addWidget(self.user_info_gb)
        self.tabWidget = QtWidgets.QTabWidget(self.win_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.chat_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chat_tab.sizePolicy().hasHeightForWidth())
        self.chat_tab.setSizePolicy(sizePolicy)
        self.chat_tab.setObjectName("chat_tab")
        self.tabWidget.addTab(self.chat_tab, "")
        self.conversation = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conversation.sizePolicy().hasHeightForWidth())
        self.conversation.setSizePolicy(sizePolicy)
        self.conversation.setStyleSheet("")
        self.conversation.setObjectName("conversation")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.conversation)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chat_list = QtWidgets.QToolBox(self.conversation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chat_list.sizePolicy().hasHeightForWidth())
        self.chat_list.setSizePolicy(sizePolicy)
        self.chat_list.setStyleSheet("")
        self.chat_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.chat_list.setFrameShadow(QtWidgets.QFrame.Plain)
        self.chat_list.setLineWidth(0)
        self.chat_list.setObjectName("chat_list")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 254, 553))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page.sizePolicy().hasHeightForWidth())
        self.page.setSizePolicy(sizePolicy)
        self.page.setObjectName("page")
        self.chat_list.addItem(self.page, icon2, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 254, 549))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_2.sizePolicy().hasHeightForWidth())
        self.page_2.setSizePolicy(sizePolicy)
        self.page_2.setObjectName("page_2")
        self.chat_list.addItem(self.page_2, icon2, "")
        self.verticalLayout.addWidget(self.chat_list)
        self.tabWidget.addTab(self.conversation, "")
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_2.setStretch(1, 6)
        self.verticalLayout_2.setStretch(2, 99)
        MainWindow.setCentralWidget(self.win_container)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.chat_list.setCurrentIndex(0)
        self.chat_list.layout().setSpacing(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.avatar.setText(_translate("MainWindow", "..."))
        self.user_nane.setText(_translate("MainWindow", "userName"))
        self.sign.setText(_translate("MainWindow", "sign"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chat_tab), _translate("MainWindow", "聊天"))
        self.chat_list.setItemText(self.chat_list.indexOf(self.page), _translate("MainWindow", "Page 1"))
        self.chat_list.setItemText(self.chat_list.indexOf(self.page_2), _translate("MainWindow", "Page 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.conversation), _translate("MainWindow", "通讯录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "暂定页"))
from src import img_rc
