# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(294, 568)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(21)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/src/icon/icon/人群.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow#background-image: url(:/src/images/images/main_bg1.png);")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AnimatedDocks)
        self.win_container = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.win_container.sizePolicy().hasHeightForWidth())
        self.win_container.setSizePolicy(sizePolicy)
        self.win_container.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.win_container.setStyleSheet("")
        self.win_container.setObjectName("win_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.win_container)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.top_btn_gb = QtWidgets.QGroupBox(self.win_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_btn_gb.sizePolicy().hasHeightForWidth())
        self.top_btn_gb.setSizePolicy(sizePolicy)
        self.top_btn_gb.setObjectName("top_btn_gb")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_btn_gb)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(152, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.add_btn = QtWidgets.QPushButton(self.top_btn_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_btn.sizePolicy().hasHeightForWidth())
        self.add_btn.setSizePolicy(sizePolicy)
        self.add_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.add_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/src/icon/添加好友 _1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_btn.setIcon(icon1)
        self.add_btn.setAutoRepeat(False)
        self.add_btn.setFlat(True)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.skin_btn = QtWidgets.QPushButton(self.top_btn_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skin_btn.sizePolicy().hasHeightForWidth())
        self.skin_btn.setSizePolicy(sizePolicy)
        self.skin_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.skin_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/src/icon/皮肤.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skin_btn.setIcon(icon2)
        self.skin_btn.setAutoRepeat(False)
        self.skin_btn.setFlat(True)
        self.skin_btn.setObjectName("skin_btn")
        self.horizontalLayout.addWidget(self.skin_btn)
        self.setting_btn = QtWidgets.QPushButton(self.top_btn_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setting_btn.sizePolicy().hasHeightForWidth())
        self.setting_btn.setSizePolicy(sizePolicy)
        self.setting_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.setting_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/src/icon/设置_管理.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting_btn.setIcon(icon3)
        self.setting_btn.setAutoRepeat(False)
        self.setting_btn.setFlat(True)
        self.setting_btn.setObjectName("setting_btn")
        self.horizontalLayout.addWidget(self.setting_btn)
        self.minimum_btn = QtWidgets.QPushButton(self.top_btn_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimum_btn.sizePolicy().hasHeightForWidth())
        self.minimum_btn.setSizePolicy(sizePolicy)
        self.minimum_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.minimum_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/src/icon/下拉.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimum_btn.setIcon(icon4)
        self.minimum_btn.setAutoRepeat(False)
        self.minimum_btn.setFlat(True)
        self.minimum_btn.setObjectName("minimum_btn")
        self.horizontalLayout.addWidget(self.minimum_btn)
        self.close_btn = QtWidgets.QPushButton(self.top_btn_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_btn.sizePolicy().hasHeightForWidth())
        self.close_btn.setSizePolicy(sizePolicy)
        self.close_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.close_btn.setStyleSheet("")
        self.close_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/src/icon/关闭.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon5)
        self.close_btn.setDefault(True)
        self.close_btn.setFlat(True)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        self.horizontalLayout.setStretch(4, 1)
        self.horizontalLayout.setStretch(5, 1)
        self.verticalLayout_2.addWidget(self.top_btn_gb)
        self.user_info_gb = QtWidgets.QGroupBox(self.win_container)
        self.user_info_gb.setEnabled(True)
        self.user_info_gb.setTitle("")
        self.user_info_gb.setFlat(True)
        self.user_info_gb.setObjectName("user_info_gb")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.user_info_gb)
        self.horizontalLayout_3.setContentsMargins(8, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.avatar = QtWidgets.QLabel(self.user_info_gb)
        self.avatar.setText("")
        self.avatar.setAlignment(QtCore.Qt.AlignCenter)
        self.avatar.setObjectName("avatar")
        self.horizontalLayout_3.addWidget(self.avatar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.user_nane = QtWidgets.QLabel(self.user_info_gb)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.user_nane.setFont(font)
        self.user_nane.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.user_nane.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.user_nane.setTextFormat(QtCore.Qt.AutoText)
        self.user_nane.setObjectName("user_nane")
        self.verticalLayout_3.addWidget(self.user_nane)
        self.sign = QtWidgets.QLabel(self.user_info_gb)
        self.sign.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sign.setObjectName("sign")
        self.verticalLayout_3.addWidget(self.sign)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.setStretch(2, 2)
        self.verticalLayout_3.setStretch(3, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 8)
        self.verticalLayout_2.addWidget(self.user_info_gb)
        self.tabWidget = QtWidgets.QTabWidget(self.win_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.history_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.history_tab.sizePolicy().hasHeightForWidth())
        self.history_tab.setSizePolicy(sizePolicy)
        self.history_tab.setObjectName("history_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.history_tab)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.history_list = QtWidgets.QListWidget(self.history_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.history_list.sizePolicy().hasHeightForWidth())
        self.history_list.setSizePolicy(sizePolicy)
        self.history_list.setAutoScrollMargin(0)
        self.history_list.setResizeMode(QtWidgets.QListView.Adjust)
        self.history_list.setObjectName("history_list")
        self.verticalLayout_4.addWidget(self.history_list)
        self.tabWidget.addTab(self.history_tab, "")
        self.conversation = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conversation.sizePolicy().hasHeightForWidth())
        self.conversation.setSizePolicy(sizePolicy)
        self.conversation.setStyleSheet("")
        self.conversation.setObjectName("conversation")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.conversation)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chat_list = QtWidgets.QTreeWidget(self.conversation)
        self.chat_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chat_list.setAutoScrollMargin(0)
        self.chat_list.setIndentation(0)
        self.chat_list.setAnimated(True)
        self.chat_list.setObjectName("chat_list")
        self.chat_list.headerItem().setText(0, "1")
        self.chat_list.header().setVisible(False)
        self.verticalLayout.addWidget(self.chat_list)
        self.tabWidget.addTab(self.conversation, "")
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.room_list = QtWidgets.QListWidget(self.tab)
        self.room_list.setObjectName("room_list")
        self.verticalLayout_5.addWidget(self.room_list)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_2.setStretch(1, 10)
        self.verticalLayout_2.setStretch(2, 99)
        MainWindow.setCentralWidget(self.win_container)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.user_nane.setText(_translate("MainWindow", "userName"))
        self.sign.setText(_translate("MainWindow", "暂无"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.history_tab), _translate("MainWindow", "聊天"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.conversation), _translate("MainWindow", "通讯录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "群聊发现"))
from src import img_rc
