# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_win(object):
    def setupUi(self, register_win):
        register_win.setObjectName("register_win")
        register_win.resize(389, 287)
        self.verticalLayout = QtWidgets.QVBoxLayout(register_win)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalFrame = QtWidgets.QFrame(register_win)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_8.setContentsMargins(4, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.from_jid = QtWidgets.QLabel(self.horizontalFrame)
        self.from_jid.setMinimumSize(QtCore.QSize(180, 0))
        self.from_jid.setText("")
        self.from_jid.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.from_jid.setObjectName("from_jid")
        self.horizontalLayout_8.addWidget(self.from_jid)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.top_btn_gb = QtWidgets.QFrame(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_btn_gb.sizePolicy().hasHeightForWidth())
        self.top_btn_gb.setSizePolicy(sizePolicy)
        self.top_btn_gb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.top_btn_gb.setObjectName("top_btn_gb")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.top_btn_gb)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.minimum_btn = QtWidgets.QPushButton(self.top_btn_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimum_btn.sizePolicy().hasHeightForWidth())
        self.minimum_btn.setSizePolicy(sizePolicy)
        self.minimum_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.minimum_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/src/icon/下拉.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimum_btn.setIcon(icon)
        self.minimum_btn.setAutoRepeat(False)
        self.minimum_btn.setFlat(True)
        self.minimum_btn.setObjectName("minimum_btn")
        self.horizontalLayout_9.addWidget(self.minimum_btn)
        self.close_btn = QtWidgets.QPushButton(self.top_btn_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_btn.sizePolicy().hasHeightForWidth())
        self.close_btn.setSizePolicy(sizePolicy)
        self.close_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.close_btn.setStyleSheet("")
        self.close_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/src/icon/关闭.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon1)
        self.close_btn.setDefault(True)
        self.close_btn.setFlat(True)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_9.addWidget(self.close_btn)
        self.horizontalLayout_8.addWidget(self.top_btn_gb)
        self.horizontalLayout_8.setStretch(1, 8)
        self.horizontalLayout_8.setStretch(2, 3)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.line = QtWidgets.QFrame(register_win)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalWidget = QtWidgets.QWidget(register_win)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(-1, 2, -1, -1)
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setVerticalSpacing(4)
        self.formLayout.setObjectName("formLayout")
        self.username = QtWidgets.QLineEdit(self.horizontalWidget)
        self.username.setMinimumSize(QtCore.QSize(0, 30))
        self.username.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.username.setMaxLength(32)
        self.username.setObjectName("username")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.username)
        self.nickname = QtWidgets.QLineEdit(self.horizontalWidget)
        self.nickname.setMinimumSize(QtCore.QSize(0, 30))
        self.nickname.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.nickname.setMaxLength(32)
        self.nickname.setObjectName("nickname")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nickname)
        self.password = QtWidgets.QLineEdit(self.horizontalWidget)
        self.password.setMinimumSize(QtCore.QSize(0, 30))
        self.password.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.password.setMaxLength(32)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.password)
        self.password_check = QtWidgets.QLineEdit(self.horizontalWidget)
        self.password_check.setMinimumSize(QtCore.QSize(0, 30))
        self.password_check.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.password_check.setInputMask("")
        self.password_check.setMaxLength(32)
        self.password_check.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_check.setObjectName("password_check")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.password_check)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.usericon = QtWidgets.QToolButton(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usericon.sizePolicy().hasHeightForWidth())
        self.usericon.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/src/images/CustomerCopy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.usericon.setIcon(icon2)
        self.usericon.setIconSize(QtCore.QSize(60, 60))
        self.usericon.setAutoExclusive(True)
        self.usericon.setObjectName("usericon")
        self.horizontalLayout_7.addWidget(self.usericon)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_7)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 4, -1, 8)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.register_btn = QtWidgets.QPushButton(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.register_btn.sizePolicy().hasHeightForWidth())
        self.register_btn.setSizePolicy(sizePolicy)
        self.register_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.register_btn.setDefault(False)
        self.register_btn.setFlat(False)
        self.register_btn.setObjectName("register_btn")
        self.horizontalLayout_12.addWidget(self.register_btn)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.horizontalLayout_3.addLayout(self.formLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.horizontalWidget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 99)

        self.retranslateUi(register_win)
        QtCore.QMetaObject.connectSlotsByName(register_win)

    def retranslateUi(self, register_win):
        _translate = QtCore.QCoreApplication.translate
        register_win.setWindowTitle(_translate("register_win", "Dialog"))
        self.usericon.setText(_translate("register_win", "..."))
        self.register_btn.setText(_translate("register_win", "注册"))
from src import img_rc
