# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'room_item.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(280, 65)
        Form.setMinimumSize(QtCore.QSize(280, 65))
        Form.setMaximumSize(QtCore.QSize(280, 50))
        self.itemLayout = QtWidgets.QHBoxLayout(Form)
        self.itemLayout.setContentsMargins(10, 2, 5, 2)
        self.itemLayout.setSpacing(0)
        self.itemLayout.setObjectName("itemLayout")
        self.infoWidget = QtWidgets.QWidget(Form)
        self.infoWidget.setObjectName("infoWidget")
        self.formLayout = QtWidgets.QFormLayout(self.infoWidget)
        self.formLayout.setContentsMargins(3, 2, 0, 2)
        self.formLayout.setHorizontalSpacing(1)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(self.infoWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.room_name = QtWidgets.QLabel(self.infoWidget)
        self.room_name.setObjectName("room_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.room_name)
        self.moodLabel = QtWidgets.QLabel(self.infoWidget)
        self.moodLabel.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.moodLabel.setStyleSheet("color: rgb(188, 188, 188);")
        self.moodLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.moodLabel.setObjectName("moodLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.moodLabel)
        self.description = QtWidgets.QLabel(self.infoWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(188, 188, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 188, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.description.setPalette(palette)
        self.description.setObjectName("description")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.description)
        self.nameLabel_2 = QtWidgets.QLabel(self.infoWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(188, 188, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 188, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 196, 196, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 188, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 188, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 196, 196, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.nameLabel_2.setPalette(palette)
        self.nameLabel_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.nameLabel_2.setObjectName("nameLabel_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.nameLabel_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.create_time = QtWidgets.QLabel(self.infoWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(188, 188, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 188, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.create_time.setPalette(palette)
        self.create_time.setObjectName("create_time")
        self.horizontalLayout.addWidget(self.create_time)
        self.member = QtWidgets.QLabel(self.infoWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(188, 188, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 188, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.member.setPalette(palette)
        self.member.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.member.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.member.setObjectName("member")
        self.horizontalLayout.addWidget(self.member)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 1)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.itemLayout.addWidget(self.infoWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.nameLabel.setText(_translate("Form", "房间名称："))
        self.room_name.setText(_translate("Form", "Pyqt讨论组"))
        self.moodLabel.setText(_translate("Form", "房间简介："))
        self.description.setText(_translate("Form", "pyqt交流学习"))
        self.nameLabel_2.setText(_translate("Form", "创建时间："))
        self.create_time.setText(_translate("Form", "2020-01-01"))
        self.member.setText(_translate("Form", "10/30"))
